# Generated by Django 4.2.28 on 2026-03-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_sessio_student__7d3f13_idx_user_sessio_student_9228b7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('avatar', 'Аватар'), ('banner', 'Баннер')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.user')),
            ],
            options={
                'db_table': 'user_profile_media',
            },
        ),
        migrations.CreateModel(
            name='MediaOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('thumbnail', 'Миниатюра 150x150'), ('small', 'Маленький 300x300'), ('medium', 'Средний 800x600'), ('large', 'Большой 1200x800')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_versions', to='api.userprofilemedia')),
            ],
            options={
                'db_table': 'media_optimizations',
            },
        ),
        migrations.AddIndex(
            model_name='userprofilemedia',
            index=models.Index(fields=['user', 'media_type', 'is_active'], name='user_profil_user_id_5002fb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilemedia',
            index=models.Index(fields=['created_at'], name='user_profil_created_f9bb79_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaoptimization',
            index=models.Index(fields=['original_media', 'size_type'], name='media_optim_origina_9427f4_idx'),
        ),
    ]
