# Generated by Django 4.2.28 on 2026-03-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_last_login_user_last_login_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Примечания о назначении')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='api.user')),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointed_admins', to='api.user')),
            ],
            options={
                'db_table': 'administration',
                'indexes': [models.Index(fields=['administrator', 'is_active'], name='administrat_adminis_b89289_idx'), models.Index(fields=['appointed_by'], name='administrat_appoint_697abe_idx'), models.Index(fields=['appointed_at'], name='administrat_appoint_6ee24d_idx')],
            },
        ),
    ]
