# Generated by Django 4.2.28 on 2026-03-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
