# Generated by Django 4.2.28 on 2026-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_ban_end_date_user_ban_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ban_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ban_reason',
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=10)),
                ('user_id', models.IntegerField(db_index=True)),
                ('banned_by_id', models.IntegerField(blank=True, null=True)),
                ('ban_date', models.DateTimeField(auto_now_add=True)),
                ('ban_duration_seconds', models.IntegerField()),
                ('ban_reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_bans',
                'indexes': [models.Index(fields=['student_code', 'is_active'], name='user_bans_student_f747ec_idx'), models.Index(fields=['user_id', 'is_active'], name='user_bans_user_id_0ec7f3_idx'), models.Index(fields=['banned_by_id'], name='user_bans_banned__afb79c_idx'), models.Index(fields=['ban_date'], name='user_bans_ban_dat_1ac94b_idx'), models.Index(fields=['created_at'], name='user_bans_created_e0458c_idx')],
            },
        ),
    ]
