# Generated by Django 4.2.28 on 2026-03-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_ban_end_date_remove_user_ban_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
    ]
