# Generated by Django 4.2.28 on 2026-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userban',
            name='unban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userban',
            name='unbanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userban',
            name='unbanned_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['unbanned_by_id'], name='user_bans_unbanne_c272fe_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['unbanned_at'], name='user_bans_unbanne_04d113_idx'),
        ),
    ]
