# Generated by Django 4.2.28 on 2026-03-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userban_unban_reason_userban_unbanned_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userban',
            name='user_bans_unbanne_c272fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='userban',
            name='user_bans_unbanne_04d113_idx',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='unban_reason',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='unbanned_at',
        ),
        migrations.RemoveField(
            model_name='userban',
            name='unbanned_by_id',
        ),
    ]
